/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

plugins {
    kotlin("jvm") version "2.1.20"
    kotlin("plugin.serialization") version "2.1.20"
    application
}


repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0")


    
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.0") // Example dependency
}

// Specify the main class for your application
application {
    mainClass.set("com.example.MainKt") // Replace with your actual main class path
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "com.example.MainKt" // Replace with your actual main class path
    }
}

tasks.test {
    useJUnitPlatform()
}
